team_codes = [
    'ATL',
    'BOS',
    'BRK',
    'CHI',
    'CHO',
    'CLE',
    'DAL',
    'DEN',
    'DET',
    'GSW',
    'HOU',
    'IND',
    'LAC',
    'LAL',
    'MEM',
    'MIA',
    'MIL',
    'MIN',
    'NOP',
    'NYK',
    'OKC',
    'ORL',
    'PHI',
    'PHO',
    'POR',
    'SAC',
    'SAS',
    'TOR',
    'UTA',
    'WAS'
]

leaderboard_names = [
    'leaders_pts',
    'leaders_pts_per_g',
    'leaders_trb',
    'leaders_trb_per_g',
    'leaders_orb',
    'leaders_drb',
    'leaders_ast',
    'leaders_ast_per_g',
    'leaders_stl',
    'leaders_stl_per_g',
    'leaders_blk',
    'leaders_blk_per_g',
    'leaders_fg_pct',
    'leaders_ft_pct',
    'leaders_fg3_pct',
    'leaders_fg2_pct',
    'leaders_efg_pct',
    'leaders_ts_pct',
    'leaders_fg',
    'leaders_fga',
    'leaders_fg2',
    'leaders_fg2a',
    'leaders_fg3',
    'leaders_fg3a',
    'leaders_fgx',
    'leaders_ft',
    'leaders_fta',
    'leaders_mp',
    'leaders_mp_per_g',
    'leaders_tov',
    'leaders_pf',
    'leaders_per',
    'leaders_ws',
    'leaders_ows',
    'leaders_dws',
    'leaders_ws_per_48',
    'leaders_bpm',
    'leaders_obpm',
    'leaders_dbpm',
    'leaders_vorp',
    'leaders_off_rtg',
    'leaders_def_rtg',
    'leaders_usg_pct',
    'leaders_trb_pct',
    'leaders_ast_pct',
    'leaders_drb_pct',
    'leaders_stl_pct',
    'leaders_blk_pct',
    'leaders_tov_pct',
]

leaderboard_full_names = {
    'leaders_pts': 'Points',
    'leaders_pts_per_g': 'Points Per Game',
    'leaders_trb': 'Total Rebounds',
    'leaders_trb_per_g': 'Rebounds Per Game',
    'leaders_orb': 'Offensive Rebounds',
    'leaders_drb': 'Defensive Rebounds',
    'leaders_ast': 'Assists',
    'leaders_ast_per_g': 'Assists Per Game',
    'leaders_stl': 'Steals',
    'leaders_stl_per_g': 'Steals Per Game',
    'leaders_blk': 'Blocks',
    'leaders_blk_per_g': 'Blocks Per Game',
    'leaders_fg_pct': 'Field Goal %',
    'leaders_ft_pct': 'Free Throw %',
    'leaders_fg3_pct': '3-Pt Field Goal %',
    'leaders_fg2_pct': '2-Pt Field Goal %',
    'leaders_efg_pct': 'Effective Field Goal %',
    'leaders_ts_pct': 'True Shooting %',
    'leaders_fg': 'Field Goals',
    'leaders_fga': 'Field Goal Attempts',
    'leaders_fg2': '2-Pt Field Goals',
    'leaders_fg2a': '2-Pt Field Goal Attempts',
    'leaders_fg3': '3-Pt Field Goals',
    'leaders_fg3a': '3-Pt Field Goal Attempts',
    'leaders_fgx': 'Field Goals Missed',
    'leaders_ft': 'Free Throws',
    'leaders_fta': 'Free Throw Attempts',
    'leaders_mp': 'Minutes Played',
    'leaders_mp_per_g': 'Minutes Per Game',
    'leaders_tov': 'Turnovers',
    'leaders_pf': 'Personal Fouls',
    'leaders_per': 'Player Efficiency Rating',
    'leaders_ws': 'Win Shares',
    'leaders_ows': 'Offensive Win Shares',
    'leaders_dws': 'Defensive Win Shares',
    'leaders_ws_per_48': 'Win Shares Per 48 Minutes',
    'leaders_bpm': 'Box Plus/Minus',
    'leaders_obpm': 'Offensive Box Plus/Minus',
    'leaders_dbpm': 'Defensive Box Plus/Minus',
    'leaders_vorp': 'Value Over Replacement Player',
    'leaders_off_rtg': 'Offensive Rating',
    'leaders_def_rtg': 'Defensive Rating',
    'leaders_usg_pct': 'Usage %',
    'leaders_trb_pct': 'Total Rebound %',
    'leaders_ast_pct': 'Assist %',
    'leaders_drb_pct': 'Defensive Rebound %',
    'leaders_stl_pct': 'Steal %',
    'leaders_blk_pct': 'Block %',
    'leaders_tov_pct': 'Turnover %',
}

gamelog_seasons = [
    '2009-10',
    '2010-11',
    '2011-12',
    '2012-13',
    '2013-14',
    '2014-15',
    '2015-16',
    '2016-17',
    '2017-18',
    '2018-19',
    '2019-20',
    '2020-21',
    '2021-22',
    '2022-23',
]

new_leaderboard_names = [
    'GP',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PTS',
    'EFF',
]

new_team_codes = [
    'ATL',
    'BOS',
    'BKN',
    'CHA',
    'CHI',
    'CLE',
    'DAL',
    'DEN',
    'DET',
    'GSW',
    'HOU',
    'IND',
    'LAC',
    'LAL',
    'MEM',
    'MIA',
    'MIL',
    'MIN',
    'NOP',
    'NYK',
    'OKC',
    'ORL',
    'PHI',
    'PHX',
    'POR',
    'SAC',
    'SAS',
    'TOR',
    'UTA',
    'WAS',
]

team_icons = {
    'ATL': 'https://content.sportslogos.net/logos/6/220/full/8190_atlanta_hawks-primary-2021.png',
    'BOS': 'https://content.sportslogos.net/logos/6/213/full/boston_celtics_logo_primary_19977628.png',
    'BKN': 'https://content.sportslogos.net/logos/6/3786/full/brooklyn_nets_logo_primary_20135043.png',
    'CHA': 'https://content.sportslogos.net/logos/6/5120/full/1926_charlotte__hornets_-primary-2015.png',
    'CHI': 'https://content.sportslogos.net/logos/6/221/full/chicago_bulls_logo_primary_19672598.png',
    'CLE': 'https://content.sportslogos.net/logos/6/222/full/cleveland_cavaliers_logo_primary_2023_sportslogosnet-5369.png',
    'DAL': 'https://content.sportslogos.net/logos/6/228/full/3463_dallas_mavericks-primary-2018.png',
    'DEN': 'https://content.sportslogos.net/logos/6/229/full/8926_denver_nuggets-primary-2019.png',
    'DET': 'https://content.sportslogos.net/logos/6/223/full/detroit_pistons_logo_primary_20185710.png',
    'GSW': 'https://content.sportslogos.net/logos/6/235/full/3152_golden_state_warriors-primary-2020.png',
    'HOU': 'https://content.sportslogos.net/logos/6/230/full/6830_houston_rockets-primary-2020.png',
    'IND': 'https://content.sportslogos.net/logos/6/224/full/4812_indiana_pacers-primary-2018.png',
    'LAC': 'https://content.sportslogos.net/logos/6/236/full/los_angeles_clippers_logo_primary_2019_sportslogosnet-3776.png',
    'LAL': 'https://content.sportslogos.net/logos/6/237/full/uig7aiht8jnpl1szbi57zzlsh.png',
    'MEM': 'https://content.sportslogos.net/logos/6/231/full/4373_memphis_grizzlies-primary-2019.png',
    'MIA': 'https://content.sportslogos.net/logos/6/214/full/burm5gh2wvjti3xhei5h16k8e.gif',
    'MIL': 'https://content.sportslogos.net/logos/6/225/full/milwaukee_bucks_logo_primary_20165763.png',
    'MIN': 'https://content.sportslogos.net/logos/6/232/full/9669_minnesota_timberwolves-primary-2018.png',
    'NOP': 'https://content.sportslogos.net/logos/6/4962/full/2681_new_orleans_pelicans-primary-2014.png',
    'NYK': 'https://content.sportslogos.net/logos/6/216/full/2nn48xofg0hms8k326cqdmuis.gif',
    'OKC': 'https://content.sportslogos.net/logos/6/2687/full/khmovcnezy06c3nm05ccn0oj2.png',
    'ORL': 'https://content.sportslogos.net/logos/6/217/full/orlando_magic_logo_primary_20117178.png',
    'PHI': 'https://content.sportslogos.net/logos/6/218/full/7034_philadelphia_76ers-primary-2016.png',
    'PHX': 'https://content.sportslogos.net/logos/6/238/full/phoenix_suns_logo_primary_20143696.png',
    'POR': 'https://content.sportslogos.net/logos/6/239/full/9725_portland_trail_blazers-primary-2018.png',
    'SAC': 'https://content.sportslogos.net/logos/6/240/full/4043_sacramento_kings-primary-2017.png',
    'SAS': 'https://content.sportslogos.net/logos/6/233/full/2547_san_antonio_spurs-primary-2018.png',
    'TOR': 'https://content.sportslogos.net/logos/6/227/full/7024_toronto_raptors-primary-2021.png',
    'UTA': 'https://content.sportslogos.net/logos/6/234/full/utah_jazz_logo_primary_2023_sportslogosnet-8513.png',
    'WAS': 'https://content.sportslogos.net/logos/6/219/full/5671_washington_wizards-primary-2016.png',
}

nhl_team_ids = [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    28,
    29,
    30,
    52,
    53,
    54,
    55
]