team_codes = [
    'ATL',
    'BOS',
    'BRK',
    'CHI',
    'CHO',
    'CLE',
    'DAL',
    'DEN',
    'DET',
    'GSW',
    'HOU',
    'IND',
    'LAC',
    'LAL',
    'MEM',
    'MIA',
    'MIL',
    'MIN',
    'NOP',
    'NYK',
    'OKC',
    'ORL',
    'PHI',
    'PHO',
    'POR',
    'SAC',
    'SAS',
    'TOR',
    'UTA',
    'WAS'
]

leaderboard_names = [
    'leaders_pts',
    'leaders_pts_per_g',
    'leaders_trb',
    'leaders_trb_per_g',
    'leaders_orb',
    'leaders_drb',
    'leaders_ast',
    'leaders_ast_per_g',
    'leaders_stl',
    'leaders_stl_per_g',
    'leaders_blk',
    'leaders_blk_per_g',
    'leaders_fg_pct',
    'leaders_ft_pct',
    'leaders_fg3_pct',
    'leaders_fg2_pct',
    'leaders_efg_pct',
    'leaders_ts_pct',
    'leaders_fg',
    'leaders_fga',
    'leaders_fg2',
    'leaders_fg2a',
    'leaders_fg3',
    'leaders_fg3a',
    'leaders_fgx',
    'leaders_ft',
    'leaders_fta',
    'leaders_mp',
    'leaders_mp_per_g',
    'leaders_tov',
    'leaders_pf',
    'leaders_per',
    'leaders_ws',
    'leaders_ows',
    'leaders_dws',
    'leaders_ws_per_48',
    'leaders_bpm',
    'leaders_obpm',
    'leaders_dbpm',
    'leaders_vorp',
    'leaders_off_rtg',
    'leaders_def_rtg',
    'leaders_usg_pct',
    'leaders_trb_pct',
    'leaders_ast_pct',
    'leaders_drb_pct',
    'leaders_stl_pct',
    'leaders_blk_pct',
    'leaders_tov_pct',
]

leaderboard_full_names = {
    'leaders_pts': 'Points',
    'leaders_pts_per_g': 'Points Per Game',
    'leaders_trb': 'Total Rebounds',
    'leaders_trb_per_g': 'Rebounds Per Game',
    'leaders_orb': 'Offensive Rebounds',
    'leaders_drb': 'Defensive Rebounds',
    'leaders_ast': 'Assists',
    'leaders_ast_per_g': 'Assists Per Game',
    'leaders_stl': 'Steals',
    'leaders_stl_per_g': 'Steals Per Game',
    'leaders_blk': 'Blocks',
    'leaders_blk_per_g': 'Blocks Per Game',
    'leaders_fg_pct': 'Field Goal %',
    'leaders_ft_pct': 'Free Throw %',
    'leaders_fg3_pct': '3-Pt Field Goal %',
    'leaders_fg2_pct': '2-Pt Field Goal %',
    'leaders_efg_pct': 'Effective Field Goal %',
    'leaders_ts_pct': 'True Shooting %',
    'leaders_fg': 'Field Goals',
    'leaders_fga': 'Field Goal Attempts',
    'leaders_fg2': '2-Pt Field Goals',
    'leaders_fg2a': '2-Pt Field Goal Attempts',
    'leaders_fg3': '3-Pt Field Goals',
    'leaders_fg3a': '3-Pt Field Goal Attempts',
    'leaders_fgx': 'Field Goals Missed',
    'leaders_ft': 'Free Throws',
    'leaders_fta': 'Free Throw Attempts',
    'leaders_mp': 'Minutes Played',
    'leaders_mp_per_g': 'Minutes Per Game',
    'leaders_tov': 'Turnovers',
    'leaders_pf': 'Personal Fouls',
    'leaders_per': 'Player Efficiency Rating',
    'leaders_ws': 'Win Shares',
    'leaders_ows': 'Offensive Win Shares',
    'leaders_dws': 'Defensive Win Shares',
    'leaders_ws_per_48': 'Win Shares Per 48 Minutes',
    'leaders_bpm': 'Box Plus/Minus',
    'leaders_obpm': 'Offensive Box Plus/Minus',
    'leaders_dbpm': 'Defensive Box Plus/Minus',
    'leaders_vorp': 'Value Over Replacement Player',
    'leaders_off_rtg': 'Offensive Rating',
    'leaders_def_rtg': 'Defensive Rating',
    'leaders_usg_pct': 'Usage %',
    'leaders_trb_pct': 'Total Rebound %',
    'leaders_ast_pct': 'Assist %',
    'leaders_drb_pct': 'Defensive Rebound %',
    'leaders_stl_pct': 'Steal %',
    'leaders_blk_pct': 'Block %',
    'leaders_tov_pct': 'Turnover %',
}

gamelog_seasons = [
    '2009-10',
    '2010-11',
    '2011-12',
    '2012-13',
    '2013-14',
    '2014-15',
    '2015-16',
    '2016-17',
    '2017-18',
    '2018-19',
    '2019-20',
    '2020-21',
    '2021-22',
    '2022-23',
]

new_leaderboard_names = [
    'GP',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PTS',
    'EFF',
]

new_team_codes = [
    'ATL',
    'BOS',
    'BKN',
    'CHA',
    'CHI',
    'CLE',
    'DAL',
    'DEN',
    'DET',
    'GSW',
    'HOU',
    'IND',
    'LAC',
    'LAL',
    'MEM',
    'MIA',
    'MIL',
    'MIN',
    'NOP',
    'NYK',
    'OKC',
    'ORL',
    'PHI',
    'PHX',
    'POR',
    'SAC',
    'SAS',
    'TOR',
    'UTA',
    'WAS',
]
